name: Test Build And Run

on:
    push:
        branches:
            - main
    # Allow manual triggering
    workflow_dispatch:
        inputs:
            git-ref:
                description: Optional git ref (commit/branch/etc)
                required: false

jobs:

    # Single job to keep usage low
    build-and-run:
        name: Builds and runs the template
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository (Current)
              uses: actions/checkout@v3
              if: github.event.inputs.git-ref == ''
            - name: Clone Repository (Custom Ref)
              uses: actions/checkout@v3
              if: github.event.inputs.git-ref != ''
              with:
                  ref: ${{ github.event.inputs.git-ref }}
            - name: Build PHP 8 test
              run: ./test.sh php8
            - name: Build PHP 8.1 test
              run: ./test.sh php81
            - name: Build ReactPHP test
              run: ./test.sh reactphp

